#!/bin/bash
# Always-on Pacifica full-fidelity collector + R2 lifecycle loop for Fly/VPS.
# Requires R2 credentials via rclone environment variables or mounted config.

set -euo pipefail

: "${PACIFICA_FULL_FIDELITY_ROOT:=/data/pacifica_full_fidelity}"
: "${PACIFICA_FULL_FIDELITY_STATE_DB:=/data/pacifica_full_fidelity_storage.sqlite}"
: "${PACIFICA_FULL_FIDELITY_R2_PREFIX:=raw/pacifica/full_fidelity}"
: "${PACIFICA_FULL_FIDELITY_REMOTE_BASE:=r2:pacifica-trading-data}"
: "${PACIFICA_FULL_FIDELITY_RETENTION_DAYS:=1}"
: "${PACIFICA_FULL_FIDELITY_LIFECYCLE_INTERVAL_S:=1800}"
: "${PACIFICA_FULL_FIDELITY_BATCH_LIMIT:=200}"
: "${PACIFICA_FULL_FIDELITY_UPLOAD_LIMIT:=$PACIFICA_FULL_FIDELITY_BATCH_LIMIT}"
: "${PACIFICA_FULL_FIDELITY_VERIFY_LIMIT:=$PACIFICA_FULL_FIDELITY_BATCH_LIMIT}"
: "${PACIFICA_FULL_FIDELITY_FRESH_UPLOAD_LIMIT:=$PACIFICA_FULL_FIDELITY_UPLOAD_LIMIT}"
: "${PACIFICA_FULL_FIDELITY_FRESH_UPLOAD_TRANSFERS:=16}"
: "${PACIFICA_FULL_FIDELITY_FRESH_UPLOAD_CHECKERS:=32}"
: "${PACIFICA_FULL_FIDELITY_BACKLOG_UPLOAD_LIMIT:=250}"
: "${PACIFICA_FULL_FIDELITY_BACKLOG_LANE_INTERVAL_S:=21600}"
: "${PACIFICA_FULL_FIDELITY_BACKLOG_LANE_RUN_ON_MISSING_MARKER:=0}"
: "${PACIFICA_FULL_FIDELITY_RECENT_SCAN_HOURS:=12}"
: "${PACIFICA_FULL_FIDELITY_FULL_SCAN_INTERVAL_S:=21600}"
: "${PACIFICA_FULL_FIDELITY_UPLOAD_ORDER:=newest-first}"
: "${PACIFICA_FULL_FIDELITY_MIN_UPLOAD_AGE_SECONDS:=7200}"
: "${PACIFICA_FULL_FIDELITY_MIN_FREE_DISK_GB:=10}"
: "${PACIFICA_R2_PRUNE_EXECUTE:=1}"
: "${PACIFICA_FULL_FIDELITY_RAW_PAYLOAD_MODE:=compact}"
: "${PACIFICA_OPS_ROOT:=/data/ops}"
: "${PACIFICA_API_SURFACE_WATCH_INTERVAL_S:=86400}"
: "${PACIFICA_R2_RETENTION_PLAN_INTERVAL_S:=86400}"
: "${PACIFICA_R2_FRESHNESS_CHECK_INTERVAL_S:=3600}"
: "${PACIFICA_R2_FRESHNESS_STALE_AFTER_MIN:=180}"
: "${PACIFICA_R2_FRESHNESS_SAMPLE_PREFIXES:=channel=bbo/symbol=BTC,channel=book/symbol=ETH,channel=trades/symbol=BTC,channel=mark_price_candle/symbol=ICP}"
: "${PACIFICA_OPS_R2_PREFIX:=ops/pacifica/full_fidelity}"
: "${PACIFICA_OPS_UPLOAD_REPORTS:=1}"
: "${PACIFICA_OPS_COMMAND_TIMEOUT_S:=1800}"

export PACIFICA_FULL_FIDELITY_ROOT
export PACIFICA_FULL_FIDELITY_STATE_DB
export PACIFICA_FULL_FIDELITY_R2_PREFIX
export PACIFICA_FULL_FIDELITY_REMOTE_BASE
export PACIFICA_FULL_FIDELITY_RETENTION_DAYS
export PACIFICA_FULL_FIDELITY_BATCH_LIMIT
export PACIFICA_FULL_FIDELITY_UPLOAD_LIMIT
export PACIFICA_FULL_FIDELITY_VERIFY_LIMIT
export PACIFICA_FULL_FIDELITY_FRESH_UPLOAD_LIMIT
export PACIFICA_FULL_FIDELITY_FRESH_UPLOAD_TRANSFERS
export PACIFICA_FULL_FIDELITY_FRESH_UPLOAD_CHECKERS
export PACIFICA_FULL_FIDELITY_BACKLOG_UPLOAD_LIMIT
export PACIFICA_FULL_FIDELITY_BACKLOG_LANE_INTERVAL_S
export PACIFICA_FULL_FIDELITY_BACKLOG_LANE_RUN_ON_MISSING_MARKER
export PACIFICA_FULL_FIDELITY_RECENT_SCAN_HOURS
export PACIFICA_FULL_FIDELITY_FULL_SCAN_INTERVAL_S
export PACIFICA_FULL_FIDELITY_UPLOAD_ORDER
export PACIFICA_FULL_FIDELITY_MIN_UPLOAD_AGE_SECONDS
export PACIFICA_OPS_ROOT
export PACIFICA_API_SURFACE_WATCH_INTERVAL_S
export PACIFICA_R2_RETENTION_PLAN_INTERVAL_S
export PACIFICA_R2_FRESHNESS_CHECK_INTERVAL_S
export PACIFICA_R2_FRESHNESS_STALE_AFTER_MIN
export PACIFICA_R2_FRESHNESS_SAMPLE_PREFIXES
export PACIFICA_OPS_R2_PREFIX
export PACIFICA_OPS_UPLOAD_REPORTS
export PACIFICA_OPS_COMMAND_TIMEOUT_S
export PACIFICA_R2_PRUNE_EXECUTE
export PACIFICA_USE_SYSTEM_PYTHON=1

mkdir -p "$PACIFICA_FULL_FIDELITY_ROOT" /data/logs "$PACIFICA_OPS_ROOT"

lifecycle_loop() {
  while true; do
    echo "[$(date -u +%FT%TZ)] lifecycle scan/upload/verify/prune start"
    if scripts/run_pacifica_full_fidelity_r2_lifecycle.sh; then
      echo "[$(date -u +%FT%TZ)] lifecycle complete"
    else
      echo "[$(date -u +%FT%TZ)] lifecycle failed; collector disk guard remains active" >&2
    fi
    python scripts/check_pacifica_full_fidelity_health.py \
      --root "$PACIFICA_FULL_FIDELITY_ROOT" \
      --state-db "$PACIFICA_FULL_FIDELITY_STATE_DB" \
      --min-free-gb "$PACIFICA_FULL_FIDELITY_MIN_FREE_DISK_GB" \
      --max-newest-age-min 60 || true
    sleep "$PACIFICA_FULL_FIDELITY_LIFECYCLE_INTERVAL_S"
  done
}

ops_watchdog_loop() {
  while true; do
    echo "[$(date -u +%FT%TZ)] ops watchdog run start"
    if python scripts/run_pacifica_fly_ops_watchdogs.py --once; then
      echo "[$(date -u +%FT%TZ)] ops watchdog run complete"
    else
      echo "[$(date -u +%FT%TZ)] ops watchdog run reported failures" >&2
    fi
    sleep 3600
  done
}

lifecycle_loop &
LIFECYCLE_PID=$!
ops_watchdog_loop &
OPS_WATCHDOG_PID=$!

cleanup() {
  kill "$LIFECYCLE_PID" "$OPS_WATCHDOG_PID" 2>/dev/null || true
}
trap cleanup EXIT INT TERM

exec scripts/run_pacifica_full_fidelity_collector.sh
